#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
from gitlabskyline import gitlab_skyline


__author__ = "Félix Gómez"


def main():
    parser = argparse.ArgumentParser(prog="gitlab-skyline",
                                     description='Create STL from Gitlab contributions',
                                     epilog='Enjoy!')
    parser.add_argument('--domain', metavar=None, type=str, nargs="?", help='GitlabEE/CE custom domain',
                        default='https://gitlab.com')
    parser.add_argument('username', metavar=None, type=str, help='Gitlab username (without @)')
    parser.add_argument('year', metavar=None, type=int,
                        help='Year of contributions to fetch', default=2020, nargs="?")

    parser.add_argument('--max_requests', metavar=None, type=int,
                        help='Max. simultaneous requests to Gitlab. Don\'t mess with their server!', default=10,
                        nargs="?")

    args = parser.parse_args()

    domain = args.domain
    username = args.username
    max_requests = args.max_requests
    year = args.year

    gitlab_skyline(username, year, domain, max_requests)


if __name__ == '__main__':
    main()
